name: Build & Package
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          pip install ruff
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py311 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
#      - name: Test with pytest
#        run: |
#          pip install pytest
#          pytest
      - name: 'Building binaries: CLI'
        run: |
          pip install pyinstaller
          pyinstaller --name git_stats_plate_gen --console --path .venv/lib/python3.11/site-packages --onedir gspg/cli/__main__.py
      - name: 'Building binaries: GUI'
        run: |
          pip install pyinstaller
          pyinstaller --name 'Git Stats Plate Genrator' --noconsole --path .venv/lib/python3.11/site-packages --onedir gspg/gui/__main__.py
          ls -l dist
      - name: Packaging binaries
        run: |
          echo "Will be done soon"
